### ISSUE TITLE
Can this tool find Rotational-Xor differential for all ciphers that have implemented?

### ISSUE THREAD

**Issue by yuanyuan1024** [ranea/RX-difference-tool#2]
I want to find RX-Diff for lea, tea, xtea ciphers, but when I try to find RX-diff, it fails. Could you please give me some examples to find RX-Diff for some ciphers that have implemented. Thank you very much!!!!

**Comment by ranea** [comment]
The ciphers LEA, TEA and XTEA contain the operation 'modular addition by a constant'. Currently, our RX-search doesn't support ciphers including this operation (this is an open problem in academia).
